### ISSUE TITLE
Target shader applied to textures does not always only apply to the actual target

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [db0/deckbuilder#10]
Noticable with 2 gaslighters (player doesn't glow here, so not sure what's going on):

![ArcoLinux_2021-07-19_00-43-40](https://user-images.githubusercontent.com/4397725/126104197-e587d708-667a-433c-9071-0d3749debdf0.png)

Polygon-based enemies unaffected.

Happens with the boss. Screenshot with boss fixed to show outline (see issue #12, but the image here is slightly older/worse):

![ArcoLinux_2021-07-19_01-17-23](https://user-images.githubusercontent.com/4397725/126107546-78833413-3024-41c4-a9ee-db2c1d91a284.png)

I should add that this isn't showing which targets *can* be targeted effectively. It does not show before target is selected, and it will make the player glow even though it won't actually let you target yourself.

Also, doesn't happen when there is only 1 gaslighter.

------------

A semi-related thing, but it also might be good to change the color to red for effects on the player that aren't fully positive (like Nothing to Fear and Dive in)

**Comment by db0** [comment]
Yes, this is probably because the shader material is not unique on the CombatEntity scene. I noticed it too. I'll fix.
