### ISSUE TITLE
Boss cutout PNG

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [db0/deckbuilder#12]
To work with your outline shader as described in another issue. I have done it, but cannot upload the file due to it being an image and me lacking push access.

You can manually add it though, all you have to do is import and switch the file over. Here's the file:

![Narcissus](https://user-images.githubusercontent.com/4397725/126110197-1e29d0f4-f334-4349-b0a8-166bcbc47f17.png)

Note that I also denoised and posterized it. I also optimized it using Trimage which makes it smaller than the original .jpg (before optimization it was slightly larger).

You can still tell that some of the spaces (top of head, hands) don't leave enough width for the outline, but IMO it's good enough.

**Comment by db0** [comment]
Good work. Thanks!

**Comment by insomniacUNDERSCORElemon** [comment]
Something to note: while I've complained about small display size being an issue, it's actually beneficial in a case like this. (Although even at the size shown here, I don't think it's fine as-is especially with the type of texture even on the original HD version of the painting)
 
Particularly it's likely that colors (and thus size) could be reduced further, but I don't have a good way to test that (short of replacing the player image even though it displays smaller) and there actually really isn't a point here as this image is already under 400KiB.

----------------------

Although if you'd prefer I re-do this while scaling it down to get more of the empty space needed for the shader, I could try doing that. Perhaps even from the 5,951x7,205px version, for less lost detail (like from scaling multiple times) although I denoising might destroy most of the detail anyways.

**Comment by db0** [comment]
nah don't worry. This is all provisional until we get something proper.

**Comment by insomniacUNDERSCORElemon** [comment]
I get that. 

I'm just saying it wouldn't be any issue for me (maybe 5 minutes and is not at all difficult), and who knows when "something proper" will come along (could be years).

**Comment by db0** [comment]
>I'm just saying it wouldn't be any issue for me (maybe 5 minutes and is not at all difficult),

I mean, it's your time. If you want to keep improving, be my guest! :D

**Comment by insomniacUNDERSCORElemon** [comment]
Version 2. Significantly sharper and even smaller file size (188.6 KiB). No denoising done, final result is a bit grainy, but the colors are better than starting with the lower-res version.

Note that due to the larger margins at-same-size res, enemy size may need to be adjusted to compensate.

![Narcissus](https://user-images.githubusercontent.com/4397725/126258198-488c4b0d-a342-4f34-9a97-0c54e36fea31.png)

**Comment by insomniacUNDERSCORElemon** [comment]
Version 3. 

Took last version and manually painted over noise in dark areas with black, reworked cutout a bit, and properly centered.

![Narcissus](https://user-images.githubusercontent.com/4397725/126285250-460fbb19-05e6-4bbf-9621-b7ced519cae2.png)
