### ISSUE TITLE
Intent icons need a background or outline

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [db0/deckbuilder#9]
Due to certain backgrounds being bright.

![ArcoLinux_2021-07-18_21-44-54](https://user-images.githubusercontent.com/4397725/126091322-4b91b02a-add8-406c-a092-6fc1923f1008.png)

**Comment by db0** [comment]
True true. I'm trying to figure out how to do it in https://game-icons.net. Using the "stroke" property doesn't seem to work. If that doesn't work, I'll try using a shader.

**Comment by insomniacUNDERSCORElemon** [comment]
You could also just use the same circle icon you're already using on effects (like doubt), but it is ugly (aliased) due to the fine circular details being downscaled to such a low resolution. But as I've said before, small scale on the polygons is an issue too so hopefully you can eventually have both at a larger size if it's available.

You could detect bright backgrounds and invert the icons, although this might be tricky when it comes to backgrounds with high contrast... particularly if an icon can be located between light and dark (meaning you cannot use just 1 differing color).

Adding an outline with an image editor is relatively simple. Select your main color, grow the selection (I don't know what would be best here due to the size, but something 6-16px, probably... as big as you can go without it being on the edge), and then fill an entire layer black in a layer under it. You could leave your glow, but you also might want to delete it outside of the outline as well. Although this might benefit from being automated.

**Comment by insomniacUNDERSCORElemon** [comment]
> I'm trying to figure out how to do it in https://game-icons.net. Using the "stroke" property doesn't seem to work

I didn't try exporting, but otherwise seems to work for me.

However it doesn't seem to have an option for the stroke to be *behind* the icon, so the wide the stroke is set to the more some elements can look bad (due to overlapping stroke as well as losing area, whereas if it were behind the icon it wouldn't alter the icon itself).

For example:

![ArcoLinux_2021-07-19_03-53-45](https://user-images.githubusercontent.com/4397725/126123512-6f7907d2-e367-45ff-a96f-42009ec30fb5.png)

(other designs may look worse, especially with smaller details)

So I do think you're better off using some other method, like the ones I described above.

**Comment by db0** [comment]
I did figure it out. Not going to apply the stroke to all icons, as most have a dark background . I'm only applying it to intents, with a small stroke width.

Modifying everything with GIMP is more trouble than it's worth :)
